spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 9227


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9223/eureka/
feign:
  hystrix:
    enabled: true